[package]
name = "cargo-changelog"
version = "0.2.0"
edition = "2021"

authors = [ "Matthias Beyer <mail@beyermatthias.de>" ]
description = "Changelog management tool"
homepage = "https://github.com/matthiasbeyer/cargo-changelog"
repository = "https://github.com/matthiasbeyer/cargo-changelog"
license = "GPL-2.0"
readme = "./README.md"
keywords = [ "cargo", "changelog", "cli", "utility", "tool" ]
categories = [ "command-line-utilities", "development-tools", "development-tools::cargo-plugins" ]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
cargo_metadata = "0.15.2"
clap = { version = "4", features = [ "cargo", "derive", "wrap_help" ] }
comma = "1.0.0"
dialoguer = "0.10.2"
env_logger = "0.10.0"
getset = "0.1.2"
git2 = "0.15.0"
handlebars = "4.3.5"
itertools = "0.10.5"
log = "0.4.17"
miette = { version = "5.5.0", features = ["fancy"] }
semver = "1.0.16"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_yaml = "0.9.14"
thiserror = "1.0.37"
time = { version = "0.3.17", features = [ "formatting", "macros" ] }
toml = "0.5.9"
typed-builder = "0.11.0"
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "2.0.5"
indoc = "1.0.8"
predicates = "2.1.4"
tempdir = "0.3.7"
